kind: pipeline
type: docker
name: build and push docker image

trigger:
  branch:
    - main
  event:
    - push

clone:
  depth: 1
  retries: 3

steps:
  - name: build and push
    image: plugins/docker
    settings:
      username:
        from_secret: DOCKERHUB_USERNAME
      password:
        from_secret: DOCKERHUB_TOKEN
    commands:
      - docker buildx create --platform linux/arm64,linux/amd64 --use
      - docker buildx inspect --bootstrap
      - docker buildx build --file Dockerfile.arm64 --platform linux/arm64 --tag nagaseyami/chatgpt-telegram-bot:latest .
      - docker buildx build --file Dockerfile.arm64 --platform linux/arm64 --tag nagaseyami/chatgpt-telegram-bot:latest .
      - docker push nagaseyami/chatgpt-telegram-bot:latest
