kind: pipeline
type: docker
name: build and push docker image

trigger:
  branch:
    - main
  event:
    - push

clone:
  depth: 1
  retries: 3

steps:
  - name: docker buildx & push
    image: docker:dind
    volumes:
      - name: dockersock
        path: /var/run
    privileged: true
    environment:
      REGISTRY:
        from_secret: REGISTRY
      GITEA_USERNAME:
        from_secret: GITEA_USERNAME
      GITEA_ACCESS_TOKEN:
        from_secret: GITEA_ACCESS_TOKEN
    commands:
      - sleep 5
      - docker login -u $GITEA_USERNAME -p $GITEA_ACCESS_TOKEN $REGISTRY
      - docker buildx create --platform linux/amd64,linux/arm64 --use
      - docker buildx build --platform linux/amd64,linux/arm64 --tag $REGISTRY/$GITEA_USERNAME/chatgpt-telegram-bot:latest . --push

services:
  - name: docker service
    image: docker:dind
    privileged: true
    volumes:
      - name: dockersock
        path: /var/run

volumes:
  - name: dockersock
    temp: {}
