kind: pipeline
type: docker
name: build and push docker image

trigger:
  branch:
    - main
  event:
    - push

clone:
  depth: 1
  retries: 3

steps:
  - name: docker buildx & push
    image: docker:dind
    volumes:
      - name: dockersock
        path: /var/run
    privileged: true
    environment:
      DOCKERHUB_USERNAME:
        from_secret: DOCKERHUB_USERNAME
      DOCKERHUB_TOKEN:
        from_secret: DOCKERHUB_TOKEN
    commands:
      - sleep 5
      - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_TOKEN
      - docker buildx create --platform linux/amd64,linux/arm64 --use
      - docker buildx build --platform linux/amd64,linux/arm64 --tag $DOCKERHUB_USERNAME/chatgpt-telegram-bot:latest . --push

services:
  - name: docker
    image: docker:dind
    privileged: true
    volumes:
      - name: dockersock
        path: /var/run

volumes:
  - name: dockersock
    temp: {}

---
kind: pipeline
type: docker
name: sync to github

clone:
  retries: 3

steps:
  - name: git
    image: bitnami/git:latest
    environment:
      GITHUB_ACCESS_TOKEN:
        from_secret: GITHUB_ACCESS_TOKEN
    commands:
      - git config --global user.name [Bot]Drone
      - git config --global user.email drone@nagaseyami.com
      - git remote add github "https://git:${GITHUB_ACCESS_TOKEN}github.com/NagaseYami/chatgpt-telegram-bot.git"
      - git push github --force-with-lease --verbose
