name: build-and-push-docker-images

on:
  workflow_dispatch:
  push:
    branches:
      - "master"

jobs:
  docker:
    runs-on: ubuntu-latest
    environment: My Env
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push (amd64)
        uses: docker/build-push-action@v4
        with:
          file: Dockerfile.amd64
          platforms: linux/amd64
          load: true
          tags: nagaseyami/chatgpt-telegram-bot:latest

      - name: Build and push (arm64)
        uses: docker/build-push-action@v4
        with:
          file: Dockerfile.arm64
          platforms: linux/arm64
          push: true
          tags: nagaseyami/chatgpt-telegram-bot:latest
